### ISSUE TITLE
Error for harmonics with decimal prefactors

### ISSUE THREAD

**Issue by curio-sitas** [NonlinearOscillations/HarmonicBalance.jl#101]
Hi,

Some frequency driven systems exhibits a "Period-Doubling" behavior, where a response exists at half the excitation frequency.
Would it be possible to search for half frequency reponses ?

I tried : 
```julia
add_harmonic!(system_eqs, I, [0.5ω,ω])
```
But it ends up with the following error : 
```
ERROR: MethodError: no method matching isless(::ComplexF64, ::Int64)
Closest candidates are:
  isless(::Union{StatsBase.PValue, StatsBase.TestStat}, ::Real) at C:\Users\brsinquin\.julia\packages\StatsBase\XgjIN\src\statmodels.jl:90
  isless(::ArfLike, ::Integer) at C:\Users\brsinquin\.julia\packages\Arblib\PdCpA\src\predicates.jl:131
  isless(::Static.StaticInteger{X}, ::Real) where X at C:\Users\brsinquin\.julia\packages\Static\Ldb7F\src\Static.jl:455
  ...
```
when executing : ``` harmonic_eqs = get_harmonic_equations(system_eqs) ```

**Comment by jkosata** [comment]
Hello! We've definitely calculated subharmonics before (from the harmonic balance point of view, there is no "subharmonic", simply two harmonics). It works if you use `ω/2` instead of `0.5ω` . Better to use fractions than decimal prefactors, as you are relying on the harmonics being multiples of each other! 
That said, this needs a better error message :)

**Comment by curio-sitas** [comment]
> Hello! We've definitely calculated subharmonics before (from the harmonic balance point of view, there is no "subharmonic", simply two harmonics). It works if you use `ω/2` instead of `0.5ω` . Better to use fractions than decimal prefactors, as you are relying on the harmonics being multiples of each other! That said, this needs a better error message :)

Thank you for your response, it worked. But since i want to study the harmonics of the half-system excitation frequency i need tio add non integer fractionnal frequency Anzats such as : 
``` add_harmonic!(laser_eqs, I, [ω/2,ω,ω*(3/2)])```

It works with `ω/2` but not with `ω*(3/2)`, giving the same error as before. I tried it with different division or inverse multiplication expressions but i do not manage to make it work.

**Comment by jkosata** [comment]
This looks like a problem with the solver from `HomotopyContinuation.jl`  that occurs when solving _huge_ systems. I have only seen it when the number of paths ran above 10⁸ or so.

Here you're looking at 16 equations of order <= 2 , which should give a max of 2^16 = 65536 solutions. By internal symmetries this reduces to 11169 and runs ok for me:
![2023-02-19_17-53](https://user-images.githubusercontent.com/58295890/219962523-6257b52a-048d-4364-897f-8de6f55a96d9.png)

Funnily enough, your output seems like the solver is also trying to run 11169 paths ... Do other, similar-sized problems (e.g. from https://github.com/NonlinearOscillations/HarmonicBalance-notebooks ) run for you? Do you by any chance have a 32-bit OS?
