### ISSUE TITLE
Simultaneous sweep of multiple parameters for steady-state solutions

### ISSUE THREAD

**Issue by sandromiano** [NonlinearOscillations/HarmonicBalance.jl#108]
Hi,

I'm wondering if the current package implementation supports simultaneous sweep of multiple parameters for the steady-state solver.
What I'm trying to do is essentially have the coefficients of my ODE parametrized by a single index, and find the steady-state solutions for all the values of such index. Can this be mimicked by using time "T" as a parameter in the ODESolver? I see some examples doing such a thing.

The naive option is to run the steady-state solver in a for loop and updating the parameters at each iteration, but I'd like to use the multithreading feature embedded in homotopycontinuation.jl rather than having to nest threading commands (which maybe is still ok?).

Thanks!

**Comment by jkosata** [comment]
The current solver does support multiparametric sweeps, see e.g here [this example](https://nonlinearoscillations.github.io/HarmonicBalance.jl/stable/examples/parametron/)

You can define a new symbol, _c_, use it to parameterize your equations and then solve for different values of _c_ separately. _T_ is the independent ‘slow time’ variable. While in reality, a sweep is a time-dependent process, here we are investigating steady-state solutions only. These are a function of _c_. How these are traversed is a separate issue - a time-dependent problem in _T_.

Does this help?

**Comment by sandromiano** [comment]
My doubt arises from the fact that my coefficients are only known numerically as a function of a parameter, so I have them stored in arrays. Do I understand correctly that, for each coefficient, I can define a function
fn(i)
 that takes the index i as input and returns the list value, and then write the polynomial part of my ODE as

\sum{fn(i) * x^n}

where the index "i" has been defined as a swept variable?

Or can I directly give the indexed arrays in the ODE?

**Comment by jkosata** [comment]
I see, in this case the intended usage is to simply leave the parameters are they are and substitute numerical values at the point of solving, i.e., as an argument to the function `get_steady_states` . This will then return a set of solutions corresponding to the parameter values.

**Comment by sandromiano** [comment]
> I see, in this case the intended usage is to simply leave the parameters are they are and substitute numerical values at the point of solving, i.e., as an argument to the function `get_steady_states` . This will then return a set of solutions corresponding to the parameter values. 

Ah I see, thanks alot! I'll look a little more in detail in the "get_steady_states" source code, will let you know if I succeed or not! :)

**Comment by sandromiano** [comment]
Hi Jan,

I tried playing around with it, but couldn't find the correct way of entering my numerically defined ODE parameters.
I'll share a simple example of what I'm trying to do.

  _Let's say my ODE has three parameters: a1, a2, b; a1 and a2 are only known numerically, have same length and are to be swept simultaneously, let's say
  
  a1 = [1,3,7]
  a2 = [2,5,4]
  
  while
  
  b = [8,9,10,11]
  
  is a parameter independent from a1 and a2.
  I would like to perform a 2D sweep where a1 and a2 are swept simultaneously, for every value of b._
How should I organize these parameters and what would be the syntax to feed them into the `get_steady_states` function?

By going thru the source code of `get_steady_states` I understand that n-dimensional sweeps are handled by flattening some sort of meshgrid to 1D arrays, which are in the `input_array` argument of the `_get_raw_solutions` function. Correct me if I'm wrong.

Thanks,
Sandro

**Comment by jkosata** [comment]
This is correct, there really is no more you can do than doing an effective 1D scan in a parameter space of your choice. For your problem, you could just call `get_steady_states` 3 times, once with each value of `(a1, a2)`, and sweep over `b`.
