### ISSUE TITLE
Jacobian spectrum density plots (pcolormesh) have strange behaviour for missing stable solutions

### ISSUE THREAD

**Issue by jdelpino** [NonlinearOscillations/HarmonicBalance.jl#16]
In systems where no stable solutions are found, the missing values form gaps in the 1D solution plots, which is correct. However, one would expect a corresponding missing section in the 2D density plots of the Jacobian noise spectrum. This does not take place, as pcolormesh seems to fill the gaps with a continuous colored section, which is artificial and can be misleading. A solution would be to the spectrum in the noise spectrum with NaNs or Infs if no stable solutions have been found for the corresponding parameter value.

**Comment by jkosata** [comment]
Closed by #44
