### ISSUE TITLE
Make method structs

### ISSUE THREAD

**Issue by oameye** [NonlinearOscillations/HarmonicBalance.jl#204]
Instead of `method=:total_degree`, we should make method structs that can be called like `TotalDegree(; kwargs...)`. This allows to give options to the Homotopy solvers

**Comment by jkosata** [comment]
This makes sense but now the portion of the code that could be classified as "convenience functions for HomotopyContinuation" is getting pretty big. 

In retrospect, I think this would have made sense as a separate small package rather than being entangled with HB.
