### ISSUE TITLE
Error in plotting 

### ISSUE THREAD

**Issue by hk06319** [NonlinearOscillations/HarmonicBalance.jl#225]
I am trying to simulate the example "two_parametrons.ipynb" in the [https://github.com/NonlinearOscillations/HarmonicBalance-notebooks]. I am facing the issue with the subplots function.
```
f,ax = HarmonicBalance.subplots(1,5,figsize=(4*5,4))
HarmonicBalance.plot_1D_jacobian_eigenvalues(soln_1d, x="ω/2", physical=true, stable=false,filename="plot_1D_jacobian",ax=ax); 
```
`
I am getting the following error
UndefVarError: `subplots` not defined
Stacktrace:
 [1] getproperty(x::Module, f::Symbol)
   @ Base .\Base.jl:31
 [2] top-level scope
   @ In[61]:1
`
################################
Also for coupled parametrons, its not generating the plot against the following commad.
```
HarmonicBalance.plot_2D_phase_diagram(result_coupled, stable=false);
```

**Comment by oameye** [comment]
Hey @hk06319, the notebooks you are referring to are quite old and outdated. We are in the progress (see #221) of updating these notebooks. That said could you try 
```julia
plot_phase_diagram(result_coupled)
```

**Comment by oameye** [comment]
Hey, we know have a new website where we better examples and tutorials. Feel free to check it out :)
