### ISSUE TITLE
MethodError when getting harmonic equations

### ISSUE THREAD

**Issue by richellejadeT** [NonlinearOscillations/HarmonicBalance.jl#299]
I've been trying to run the function ``get_harmonic_equations()`` to solve a set of coupled differential equations that includes a defined function for a summation involving trigonometric functions. However, when I attempt to run it, I encounter a ``MethodError``. In contrast, when I use a simpler expression for the function, it works without any issues. What does this ``MethodError`` mean? Thanks!

<img width="1325" alt="Screenshot 2024-10-28 at 2 18 29 PM" src="https://github.com/user-attachments/assets/f05c49f0-b6c7-401b-b339-c249d4f936ec">

**Comment by oameye** [comment]
Can you share a MWE (Minimal working example)?

**Comment by richellejadeT** [comment]
Sure, this is some of the equation I have
``-d(ar, t) + (Dc - U0*B(cor, coi, cpr, cpi, cqr, cqi, A, x, y))*ai - k*ar - np/2*(cpr*cor+cpi*coi)``
where
```
function B(cor, coi, cpr, cpi, cqr, cqi, A, x, y)
    Bunc = 0
    for i in x
        for j in y
            Bunc += ((cor^2+coi^2)*1/A + (cpr^2+cpi^2)*4/A*sin(2*pi*i)^2*cos(2*pi*(cos(pi/3)*i+sin(pi/3)*j))^2 + (cqr^2+cqi^2)*4/A*cos(2*pi*i)^2*cos(2*pi*(cos(pi/3)*i+sin(pi/3)*j))^2
            +2*(cpr*cor+cpi*coi)*2/A*sin(2*pi*i)*cos(2*pi*(cos(pi/3)*i+sin(pi/3)*j))+2*(cqr*cor+cqi*coi)*2/A*cos(2*pi*i)*cos(2*pi*(cos(pi/3)*i+sin(pi/3)*j))+2*(cpr*cqr+cpi*cqi)*4/A*sin(2*pi*i)*cos(2*pi*i)*cos(2*pi*(cos(pi/3)*i+sin(pi/3)*j))^2)*cos(2*pi*(cos(pi/3)*i+sin(pi/3)*j))^2
        end
    end
    return Bunc
end
```
This would give me the MethodError. However, if I define ``B`` as something else like 
```
function B(cor, coi, cpr, cpi, cqr, cqi, A, x, y)
    Bunc = 0
    for i in x
        for j in y
            Bunc += cos(2*pi*(cos(pi/3)*i+sin(pi/3)*j))^2*(cor+cqi*cpr^2)
        end
    end
    return Bunc
end
```
Then it would work.

**Comment by oameye** [comment]
Can you give me a complete example that I can run on my own computer :)

**Comment by richellejadeT** [comment]
Something like this
```
@variables t ar(t) ai(t) cor(t) coi(t) cqr(t) cqi(t) cpr(t) cpi(t) Dc k np nq U0 wq wp V0 hbar w A x y;
function B(cor, coi, cpr, cpi, cqr, cqi, A, x, y)
    Bunc = 0
    for i in x
        for j in y
            Bunc += ((cor^2+coi^2)*1/A + (cpr^2+cpi^2)*4/A*sin(2*pi*i)^2*cos(2*pi*(cos(pi/3)*i+sin(pi/3)*j))^2 + (cqr^2+cqi^2)*4/A*cos(2*pi*i)^2*cos(2*pi*(cos(pi/3)*i+sin(pi/3)*j))^2
            +2*(cpr*cor+cpi*coi)*2/A*sin(2*pi*i)*cos(2*pi*(cos(pi/3)*i+sin(pi/3)*j))+2*(cqr*cor+cqi*coi)*2/A*cos(2*pi*i)*cos(2*pi*(cos(pi/3)*i+sin(pi/3)*j))+2*(cpr*cqr+cpi*cqi)*4/A*sin(2*pi*i)*cos(2*pi*i)*cos(2*pi*(cos(pi/3)*i+sin(pi/3)*j))^2)*cos(2*pi*(cos(pi/3)*i+sin(pi/3)*j))^2
        end
    end
    return Bunc
end

eqs = [
-d(ar, t) + (Dc - U0*B(cor, coi, cpr, cpi, cqr, cqi, A, x, y))*ai - k*ar - np/2*(cpr*cor+cpi*coi),
-d(ai, t) - (Dc - U0*B(cor, coi, cpr, cpi, cqr, cqi, A, x, y))*ar - k*ai +nq/2*(cqr*cor+coi*cqi),
-d(cor, t) - nq/2*ar*cqi - np/2*ai*cpi,
-d(coi, t) + nq/2*ar*cqr + np/2*ai*cpr,
-d(cqr, t)  - nq/2*ar*coi - 3*U0/4*(ar^2+ai^2)*cqi,
-d(cqi, t)  + nq/2*ar*cor + 3*U0/4*(ar^2+ai^2)*cqr,
-d(cpr, t)  - np/2*ai*coi - 3*U0/4*(ar^2+ai^2)*cpi,
-d(cpi, t)  + np/2*ai*cor + 3*U0/4*(ar^2+ai^2)*cpr
]

diff_eq = DifferentialEquation(eqs, [ar, ai, cor, coi, cqr, cqi, cpr, cpi])

add_harmonic!(diff_eq, ar, w)
add_harmonic!(diff_eq, ai, w)
add_harmonic!(diff_eq, cor, w)
add_harmonic!(diff_eq, coi, w)
add_harmonic!(diff_eq, cqr, w)
add_harmonic!(diff_eq, cqi, w)
add_harmonic!(diff_eq, cpr, w)
add_harmonic!(diff_eq, cpi, w)

harmonic_eq = get_harmonic_equations(diff_eq)
```

**Comment by oameye** [comment]
Few question:
* These eom you put in. How did you obtain those? Did you already do an averaging, e.g., RWA to obtain those?
* Looking at your eom they are period in `x` and `y`? Put you do not ad these the system. Instead you add the variable `w` whoch does not appear in your equation?

**Comment by richellejadeT** [comment]
I'm trying it out based on the eom on a paper. Though, there might be some terms missing there since I was trying to see which terms is affecting the error. I plan on letting w be the recoil frequency later on. But nonetheless, if you change the expression for Bunc then the error vanishes. Could it be the error is there because harmonic balance cannot find a solution for it?

**Comment by oameye** [comment]
I think you are thing the compute the effective equations of motion in a rotating frame which already has been rotated. Can you show me the paper. 

>Could it be the error is there because harmonic balance cannot find a solution for it?

The error happens when we are computing the new effective equations of motion symbolically. I am unsure why it happens. I'll try to isolate the term tomorrow.

**Comment by richellejadeT** [comment]
I think I now know why, it's those with a factor of 2 in Bunc. Those terms should cancel out and the function would work afterwards.
