### ISSUE TITLE
load function fails for custom defined systems, time-independent systems

### ISSUE THREAD

**Issue by jdelpino** [NonlinearOscillations/HarmonicBalance.jl#33]
The structure`eom` is not created when calling `Problem` with a time-independent ODE (which is introduced manually, not derived symbolically). As a result, the `load` function fails, 

`UndefRefError: access to undefined reference

Stacktrace:
 [1] getproperty
   @ ./Base.jl:42 [inlined]
 [2] _parse_symbol_names(x::Problem)
   @ HarmonicBalance ~/.julia/packages/HarmonicBalance/1VZoW/src/saving.jl:74
 [3] _parse_symbol_names(x::Result)
   @ HarmonicBalance ~/.julia/packages/HarmonicBalance/1VZoW/src/saving.jl:79
 [4] load(filename::String)
   @ HarmonicBalance ~/.julia/packages/HarmonicBalance/1VZoW/src/saving.jl:44`

**Comment by jkosata** [comment]
This is correct but the suggested usage does not require HarmonicBalance at all, so there is probably no need to implement this.
