### ISSUE TITLE
Interactive plotting is no longer a feature

### ISSUE THREAD

**Issue by jdelpino** [NonlinearOscillations/HarmonicBalance.jl#46]

**Comment by oameye** [comment]
Sadly, not many `Plots.jl` backends support this. I think only Plotly supports this.

**Comment by jkosata** [comment]
I think you can use Plotly as a backend of `Plots.jl`, see https://docs.juliaplots.org/latest/backends/

**Comment by oameye** [comment]
Is this something we still want? What was implemented before? What can we gain? Can maybe someone (@jdelpino @jkosata ) make a list of what is wanted?
