### ISSUE TITLE
Use precompilation

### ISSUE THREAD

**Issue by jkosata** [NonlinearOscillations/HarmonicBalance.jl#53]
Just-in-time compilation times are getting pretty crazy (minutes). Most of the time, similar functions are used - `get_harmonic_equations` and `get_steady_states`. Precompilation could make this much more convenient. 

Starting resource: https://julialang.org/blog/2021/01/precompile_tutorial/

**Comment by jkosata** [comment]
More investigation using `@code_warntype` shows type instabilities in the symbolic manipulation. Links to https://github.com/JuliaSymbolics/Symbolics.jl/issues/626

**Comment by jkosata** [comment]
Closer inspection shows things are quite complex. 

`@time_imports using HarmonicBalance` shows that out of the ~60s, only 8s is HarmonicBalance, the rest are dependencies.  A flamegraph shows that little time is spent on time inference, ruling out an easy fix. 

More resources: https://discourse.julialang.org/t/taking-ttfx-seriously-can-we-make-common-packages-faster-to-load-and-use/74949/49

**Comment by jkosata** [comment]
using `SnoopCompile.@snoopr` reveals there is a huge amount of invalidation coming from Arblib triggering the recompilation of some parts of `OrdinaryDiffEq` .

**Comment by oameye** [comment]
That most time was spent on compilation on dependencies rather than our own code I already suspected. We use the most notorious packages for precompilation time. Luckily, on Juliacon 2022 I picked up that a lot of the Julia masterminds are working on the problem. https://www.youtube.com/watch?v=N4h46_TCmGc

**Comment by oameye** [comment]
Looked into `SnoopCompile.jl` and the PR. Very cool stuff. Handy how it all just can be done by one macro. Nice that you also only added the less overhead `SnoopPrecompile.jl` version. Did you do a full analyses of the type instability with `JET.jl` as the documentation of `SnoopCompile.jl` suggests?
