### ISSUE TITLE
A keyword to control the loading bar

### ISSUE THREAD

**Issue by oameye** [NonlinearOscillations/HarmonicBalance.jl#60]
It would be nice to opt out on showing a load bar as it is not so compatible with the jupyter notebook and you get sometimes get crazy long output, 
![image](https://user-images.githubusercontent.com/57623933/196245543-61b22a8f-b2ce-4859-a897-64f4f0b1c03e.png)

The loading bar is a nice feature to have in the REPL tho 😄

**Comment by jkosata** [comment]
This used to be a thing, not sure why it was removed. HomotopyContinuation has it as `show_progress`, best mimic that.
