### ISSUE TITLE
Distinguishing numerical zeroes from complex numbers

### ISSUE THREAD

**Issue by oameye** [NonlinearOscillations/HarmonicBalance.jl#61]
When plotting this minimal example for a amplitude sweep
```julia
using HarmonicBalance, Plots
using Plots

@variables t x(t) 
@parameters ω ω0 F0 Γ λ θ β ψ η
natural_equation = d(d(x, t), t) + Γ*d(x, t) + ω0^2*(1-λ*cos(2*ω*t + ψ))*x + β*x^3 + η*d(x, t)*x^2
forces = F0*cos(ω*t + θ)
diff_eq = DifferentialEquation(natural_equation ~ forces, x)

add_harmonic!(diff_eq, x, ω);
harmonic_eq = get_harmonic_equations(diff_eq);

varied = ω => LinRange(0.75, 1.25, 50)
fixed = Dict(ω0 => 1.0, Γ => 0.01, F0 => 0.0, β => 1.0, λ => 0.03, η => 0.0, θ => 0.0, ψ => 0.0)
result = get_steady_states(harmonic_eq, varied, fixed, random_warmup = false)
plot1 = plot(result, "sqrt(u1^2+v1^2)")
```
I get a warning that some values with non-negligible complex parts have been projected on the real axis. Although the comples part are negliable (powers to the -51). It would be nice if only warning were issued if the complex part higher than some threshold. Something like 1e-3 maybe.

![image](https://user-images.githubusercontent.com/57623933/197403820-13ac62e9-16a6-4e67-9e16-94148a9bb951.png)

**Comment by oameye** [comment]
Could maybe the global variable `HarmonicBalance.set_imaginary_tolerance(x::Float64)` be used for this. Would be a quick fix.

**Comment by jkosata** [comment]
This is already in place, see  function `is_real` and global variable `im_tol`. The problem is how to treat numerical zeros - these appear as very small numbers, whose complex argument is random. Currently there is a cutoff 1e-70 to distinguish this.

**Comment by oameye** [comment]
Ha, I see. Maybe, the cutoff `abs(x) < 1e-70` is a bit overdoing it. Or are values smaller than 1e-20 for some examples important?

**Comment by oameye** [comment]
So I conclude here the conversion I had with @jdelpino and @jkosata about this problem.
There are two problems to tackle:
1) First, the code gives a warning when some values are clearly neglectable. This is because it is unclear how to treat the very small numbers, whose complex argument is random. There is a cutoff `abs(x) < 1e-70` which addresses this issue but depending on the physical problem and parameters overshoots the neglectable values. However, in the case someone has come across relevant (non-neglectable) really small values in their problem, one can rescale it to regular sized values. As most users will have a scientific education, we will assume this knowledge from the user, and enlarge the cutoff to `10e-20`.
2) The second problem is that these many warnings are not anyway useful. If we could collect them in a single one, that'd be optimal. Nevertheless, @jkosata was already aware of this matter and this seems not so trivial to implement.

**Comment by oameye** [comment]
We raised the cutoff `abs(x) < 1e-70` in pull request #72. However, after a discussion, we concluded that we must instead lower the cutoff `abs(x) < 1e-70` again and solve the warning issue.
