### ISSUE TITLE
Instability in computing steady states for certain parameter ranges

### ISSUE THREAD

**Issue by oameye** [NonlinearOscillations/HarmonicBalance.jl#62]
When plotting the stability diagram of the parametron with the following code,
```julia

using HarmonicBalance, ModelingToolkit, Plots

@variables t x(t) # symbolic variables
@parameters ω ω0 F0 Γ λ θ β ψ η
natural_equation = d(d(x, t), t) + Γ*d(x, t) + ω0^2*(1-λ*cos(2*ω*t + ψ))*x + β*x^3 + η*d(x, t)*x^2
forces = F0*cos(ω*t + θ)
diff_eq = DifferentialEquation(natural_equation ~ forces, x)

add_harmonic!(diff_eq, x, ω);
harmonic_eq = get_harmonic_equations(diff_eq);

varied_stability = (ω => LinRange(0.95, 1.05, 100), λ => LinRange(1e-6, 0.06, 100))
fixed_stability = Dict(ω0 => 1.0, Γ => 0.01, F0 => 0.0, β => 1.0, η => 0.3, θ => 0.0, ψ => 0.0)
result_stability = get_steady_states(harmonic_eq, varied_stability, fixed_stability);
plot_stability = plot_phase_diagram(result_stability, class= "stable", title = "η=$(fixed_stability[η])")
```
we find instability in computing steady states for certain parameter ranges.
![plot_2](https://user-images.githubusercontent.com/57623933/196417772-71ef2433-fe9e-4023-b3f6-a17f0f796a09.png)

This is caused by the fact `random_warmup` is set to `true` (probably) by default in `get_steady_states`. It seems the algorithm is not converging to all solutions, as it is doing the parameter homotopy from a system of polynomial that was adequate for a given parameter, but is not working well when you change the parameters of your system. The way that we implemented a fix is to start tracking the solutions from a trivial polynomial system which we know has the maximum number of solutions possible. This you do setting `random_warmup = false` in get steadystates.

It doesn't seem to be a problem we can solve, it might be more of an issue for the [HomotopyContinuation.jl](https://www.juliahomotopycontinuation.org/) people.

A fix for now is setting `random_warmup = false` in `get_steady_states` function.

**Comment by jkosata** [comment]
We’ve seen this with coupled parametrons too, seems like neither `false` nor `true` is an optimal default setting. Does this noise also appear when plotting `class=“all”` ? Just to make sure it’s not due to misclassification …

**Comment by oameye** [comment]
It does seem to come from the Homotopy calculation
![plot_5](https://user-images.githubusercontent.com/57623933/196901160-6fe428eb-5b3f-4704-b5c5-7ddb5a3e40f0.png)
![plot_6](https://user-images.githubusercontent.com/57623933/196901167-d2b92417-46f2-49d3-8ddf-a5e78b4618ef.png)
![plot_7](https://user-images.githubusercontent.com/57623933/196901169-14822c3e-0692-4069-89c2-f04ea4c79622.png)
![plot_8](https://user-images.githubusercontent.com/57623933/196901170-1cb9f10f-b102-480c-9500-1aef8393cf19.png)
![plot_9](https://user-images.githubusercontent.com/57623933/196901174-855223c9-4463-4c5c-b8f1-7a0bcf224f45.png)

**Comment by oameye** [comment]
The next step will be to make a minimal example in the `HomotopyContinuation.jl` framework and open an issue at [HomotopyContinuation.jl](https://github.com/JuliaHomotopyContinuation/HomotopyContinuation.jl/issues).
