### ISSUE TITLE
Change DataStructures.jl dependency with OrderedCollections.jl

### ISSUE THREAD

**Issue by oameye** [NonlinearOscillations/HarmonicBalance.jl#71]
### Discussed in https://github.com/NonlinearOscillations/HarmonicBalance.jl/discussions/70

<div type='discussions-op-text'>

<sup>Originally posted by **oameye** October 25, 2022</sup>
Hey hey, I noticed that we use DataStructures.jl, the parent of OrderedCollections.jl. However, I think, we only use the `OrderedDict` type defined in OrderedCollections.jl. Hence, we only need the  OrderedCollections.jl dependency. Although, opting for OrderedCollections.jl would not reduce are loading time by much. I think it is just cleaner to only load what you use. This is also suggested in the [SCIML style guide](https://docs.sciml.ai/SciMLStyle/dev/#Subpackaging-and-interface-packages-is-preferred-over-conditional-modules-via-Requires.jl).

![image](https://user-images.githubusercontent.com/57623933/197769532-428ef6b6-681d-416d-a7a2-9eeebb099797.png)
</div>

**Comment by jkosata** [comment]
You're right, `DataStructures` is only brought in to have `OrderedDict`
