### ISSUE TITLE
Still plot stable steady states full and unstable dashed when `class=physical` 

### ISSUE THREAD

**Issue by oameye** [NonlinearOscillations/HarmonicBalance.jl#75]
Plotting when the keyword `class=default` and `class=physical` gives different results although the same solution are shown.
Indeed running
```julia
using HarmonicBalance, Plots

@variables t x(t) # symbolic variables
@variables ω ω0 Γ λ β η
natural_equation = d(d(x, t), t) + Γ*d(x, t) + ω0^2*(1-λ*cos(2*ω*t))*x + β*x^3 + η*d(x, t)*x^2
diff_eq = DifferentialEquation(natural_equation, x)

add_harmonic!(diff_eq, x, ω);
harmonic_eq = get_harmonic_equations(diff_eq);

varied_stability = (ω => LinRange(0.98, 1.03, 100))
fixed_stability = Dict(ω0 => 1.0, Γ => 0.01, β => 1.0, η => 0.3, λ => 0.03)
result_stability = get_steady_states(harmonic_eq, varied_stability, fixed_stability, threading=true, random_warmup = false)

plot_stability = plot(result_stability, x="ω", y="sqrt(u1^2 + v1^2)")
```
yields
![image](https://user-images.githubusercontent.com/57623933/198385132-0841a33f-6b68-4a7f-bb8a-12f4bbd2944e.png)
whereas,
```julia
plot_stability = plot(result_stability, x="ω", y="sqrt(u1^2 + v1^2)", class = "physical")
```
![image](https://user-images.githubusercontent.com/57623933/198385260-3ceffd92-e33d-47be-85b3-a383d761da60.png)

**Comment by jkosata** [comment]
I don't think this is an issue. You would usually use `class` and `not_class` to plot precisely what you mean to. Implementing default behaviour that only gets triggered by a specific manual input causes more problems than it solves imho.

To replicate the default behaviour:
`plot(result_stability, class=["physical, "stable"])`
`plot!(result_stability, class="physical", not_class="stable", style=:dash)`
