### ISSUE TITLE
Linear response spectrum in the rotating frame

### ISSUE THREAD

**Issue by jdelpino** [NonlinearOscillations/HarmonicBalance.jl#97]
Functions to retrieve the linear fluctuation spectrum in the lab frame already exist. Rotating frame spectrum can be useful to compare to e.g. lock-in amplifiers measurement

**Comment by jkosata** [comment]
This can be achieved via the Jacobian - a function stored in `Result.jacobian` which takes solutions and returns jacobian matrices
e.g. to get solution 1, branch 2,  `J = result.jacobian( result[1][2]  ) `

The eigenvalues of `J` then give the fluctuation spectrum (which is very prone to misinterpretation).
